version: "3.8"
services:
  postgresdb:
    container_name: quotes-postgres
    build: 
      context: ./database
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    container_name: quotes-backend
    build:
      context: ./backend
      args:
        JAR_FILE: build/libs/quotes-0.0.1-SNAPSHOT.jar
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8080:8080
    #env_file:
    #  - ./env/backend.env
    depends_on:
      - postgresdb
  frontend:
    container_name: quotes-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 80:80
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data: