# Używamy oficjalnego obrazu MySQL
FROM mysql:8.0

# Ustawienie zmiennych środowiskowych
ENV MYSQL_DATABASE=mysql_db
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=password
ENV MYSQL_ROOT_PASSWORD=password

EXPOSE 3306
